# Changes here will be overwritten by Copier
_commit: aeb60d2
_src_path: gh:/data-tree-house/py-template
include_pytests: false
is_streamlit_app: true
library_installs:
- loguru
project_author: Johandielangman
project_description: Every company needs a theme. This is ours.
project_name: Theme Demo
project_slug: theme_demo
